package com.code.java.course.gfg.Week2.recursion.problems;

import java.util.ArrayList;

public class PossibleWordsFromPhoneDigits {
    /**
     * Given a keypad as shown in the diagram, and an array arr[ ], your task is to list all possible words in any order which can be generated by pressing numbers from array.



Examples :

Input: arr[] = [2, 3, 4]
Output: adg adh adi aeg aeh aei afg afh afi bdg bdh bdi beg beh bei bfg bfh bfi cdg cdh cdi ceg ceh cei cfg cfh cfi 
Explanation: When we press 2, 3, 4 total possible words are 3 x 3 x 3 = 27.
Input: arr[] =[3, 4, 5]
Output: dgj dgk dgl dhj dhk dhl dij dik dil egj egk egl ehj ehk ehl eij eik eil fgj fgk fgl fhj fhk fhl fij fik fil
Explanation: When we press 3, 4, 5 total possible words are 3 x 3 x 3 = 27.
Input: arr[] =[2]
Output: a b c
Explanation: When we press 2 total possible words are 3.
Constraints:
1 ≤ arr.size() ≤ 10
2 ≤ arr[i] ≤ 9

https://www.geeksforgeeks.org/find-possible-words-phone-digits/
     */
    // Recursive function to generate combinations
    public static void main(String[] args) {
        int[] arr = {2, 3};
        ArrayList<String> words = possibleWords(arr);

        for (String word : words)
            System.out.print(word + " ");
    }
    static void possibleWordsRec(int[] arr, int index, StringBuilder prefix, 
                                         String[] padMap, ArrayList<String> res) {
        // Base case: if the prefix length matches arr size
        if (index == arr.length) {
            res.add(prefix.toString());
            return;
        }

        // Get the corresponding digit
        int digit = arr[index];

        // Skip invalid digits
        if (digit < 2 || digit > 9) {
            possibleWordsRec(arr, index + 1, prefix, padMap, res);
            return;
        }

        // Place all possible letters for this digit
        for (char ch : padMap[digit].toCharArray()) {
            prefix.append(ch);
            possibleWordsRec(arr, index + 1, prefix, padMap, res);
            prefix.deleteCharAt(prefix.length() - 1);
        }
    }

    // Function to find all possible letter combinations
    static ArrayList<String> possibleWords(int[] arr) {
        ArrayList<String> res = new ArrayList<>();
        String[] padMap = {"", "", "abc", "def", "ghi", "jkl",
                           "mno", "pqrs", "tuv", "wxyz"};
      
        StringBuilder prefix = new StringBuilder();

        possibleWordsRec(arr, 0, prefix, padMap, res);
        return res;
    }


}
