(function(g){var window=this;'use strict';var sob=function(a,b){a.Qa("onAutonavCoundownStarted",b)},h6=function(a,b,c){g.Nu(a.element,"ytp-suggestion-set",!!b.videoId);
var d=b.playlistId;c=b.Vg(c?c:"mqdefault.jpg");var e=null,f=null;b instanceof g.PS&&(b.lengthText?(e=b.lengthText||null,f=b.pw||null):b.lengthSeconds&&(e=g.aH(b.lengthSeconds),f=g.aH(b.lengthSeconds,!0)));var h=!!d;d=h&&"RD"===g.ZPa(d).type;var l=b instanceof g.PS?b.isLivePlayback:null,m=b instanceof g.PS?b.isUpcoming:null,n=b.author,p=b.shortViewCount,q=b.publishedTimeText,r=[],t=[];n&&r.push(n);p&&(r.push(p),t.push(p));q&&t.push(q);c={title:b.title,author:n,author_and_views:r.join(" \u2022 "),aria_label:b.ariaLabel||
g.lK("Watch $TITLE",{TITLE:b.title}),duration:e,timestamp:f,url:b.Wk(),is_live:l,is_upcoming:m,is_list:h,is_mix:d,background:c?"background-image: url("+c+")":"",views_and_publish_time:t.join(" \u2022 "),autoplayAlternativeHeader:b.Is};b instanceof g.OS&&(c.playlist_length=b.playlistLength);a.update(c)},i6=function(a){var b=a.U(),c=b.D;
g.U.call(this,{I:"a",S:"ytp-autonav-suggestion-card",W:{href:"{{url}}",target:c?b.Y:"","aria-label":"{{aria_label}}","data-is-live":"{{is_live}}","data-is-list":"{{is_list}}","data-is-mix":"{{is_mix}}","data-is-upcoming":"{{is_upcoming}}"},V:[{I:"div",Ma:["ytp-autonav-endscreen-upnext-thumbnail","ytp-autonav-thumbnail-small"],W:{style:"{{background}}"},V:[{I:"div",W:{"aria-label":"{{timestamp}}"},Ma:["ytp-autonav-timestamp"],xa:"{{duration}}"},{I:"div",Ma:["ytp-autonav-live-stamp"],xa:"Live"},{I:"div",
Ma:["ytp-autonav-upcoming-stamp"],xa:"Upcoming"},{I:"div",S:"ytp-autonav-list-overlay",V:[{I:"div",S:"ytp-autonav-mix-text",xa:"Mix"},{I:"div",S:"ytp-autonav-mix-icon"}]}]},{I:"div",Ma:["ytp-autonav-endscreen-upnext-title","ytp-autonav-title-card"],xa:"{{title}}"},{I:"div",Ma:["ytp-autonav-endscreen-upnext-author","ytp-autonav-author-card"],xa:"{{author}}"},{I:"div",Ma:["ytp-autonav-endscreen-upnext-author","ytp-autonav-view-and-date-card"],xa:"{{views_and_publish_time}}"}]});this.J=a;this.suggestion=
null;this.j=c;this.Ta("click",this.onClick);this.Ta("keypress",this.onKeyPress)},j6=function(a,b){b=void 0===b?!1:b;
g.U.call(this,{I:"div",S:"ytp-autonav-endscreen-countdown-overlay"});var c=this;this.N=b;this.G=this.K=void 0;this.C=0;this.container=new g.U({I:"div",S:"ytp-autonav-endscreen-countdown-container"});g.L(this,this.container);this.container.Ea(this.element);b=a.U();var d=b.D;this.J=a;this.suggestion=null;this.onVideoDataChange("newdata",this.J.getVideoData());this.T(a,"videodatachange",this.onVideoDataChange);this.j=new g.U({I:"div",S:"ytp-autonav-endscreen-upnext-container",W:{"aria-label":"{{aria_label}}",
"data-is-live":"{{is_live}}","data-is-list":"{{is_list}}","data-is-mix":"{{is_mix}}","data-is-upcoming":"{{is_upcoming}}"},V:[{I:"div",S:"ytp-autonav-endscreen-upnext-header"},{I:"div",S:"ytp-autonav-endscreen-upnext-alternative-header",xa:"{{autoplayAlternativeHeader}}"},{I:"a",S:"ytp-autonav-endscreen-link-container",W:{href:"{{url}}",target:d?b.Y:""},V:[{I:"div",S:"ytp-autonav-endscreen-upnext-thumbnail",W:{style:"{{background}}"},V:[{I:"div",W:{"aria-label":"{{timestamp}}"},Ma:["ytp-autonav-timestamp"],
xa:"{{duration}}"},{I:"div",Ma:["ytp-autonav-live-stamp"],xa:"Live"},{I:"div",Ma:["ytp-autonav-upcoming-stamp"],xa:"Upcoming"}]},{I:"div",S:"ytp-autonav-endscreen-video-info",V:[{I:"div",S:"ytp-autonav-endscreen-premium-badge"},{I:"div",S:"ytp-autonav-endscreen-upnext-title",xa:"{{title}}"},{I:"div",S:"ytp-autonav-endscreen-upnext-author",xa:"{{author}}"},{I:"div",S:"ytp-autonav-view-and-date",xa:"{{views_and_publish_time}}"},{I:"div",S:"ytp-autonav-author-and-view",xa:"{{author_and_views}}"}]}]}]});
g.L(this,this.j);this.j.Ea(this.container.element);d||this.T(this.j.Ga("ytp-autonav-endscreen-link-container"),"click",this.US);this.J.xb(this.container.element,this,115127);this.J.xb(this.j.Ga("ytp-autonav-endscreen-link-container"),this,115128);this.overlay=new g.U({I:"div",S:"ytp-autonav-overlay"});g.L(this,this.overlay);this.overlay.Ea(this.container.element);this.B=new g.U({I:"div",S:"ytp-autonav-endscreen-button-container"});g.L(this,this.B);this.B.Ea(this.container.element);this.cancelButton=
new g.U({I:"button",Ma:["ytp-autonav-endscreen-upnext-button","ytp-autonav-endscreen-upnext-cancel-button",b.L("web_modern_buttons")?"ytp-autonav-endscreen-upnext-button-rounded":""],W:{"aria-label":"Cancel autoplay"},xa:"Cancel"});g.L(this,this.cancelButton);this.cancelButton.Ea(this.B.element);this.cancelButton.Ta("click",this.J1,this);this.J.xb(this.cancelButton.element,this,115129);this.playButton=new g.U({I:"a",Ma:["ytp-autonav-endscreen-upnext-button","ytp-autonav-endscreen-upnext-play-button",
b.L("web_modern_buttons")?"ytp-autonav-endscreen-upnext-button-rounded":""],W:{href:"{{url}}",role:"button","aria-label":"Play next video"},xa:"Play Now"});g.L(this,this.playButton);this.playButton.Ea(this.B.element);this.playButton.Ta("click",this.US,this);this.J.L("web_player_autonav_next_button_renderer")?(this.J.ag(this.playButton.element,this.playButton,!0),(b=this.J.getVideoData())&&tob(this,b)):this.J.xb(this.playButton.element,this,115130);this.D=new g.Bu(function(){uob(c)},500);
g.L(this,this.D);this.SS();this.T(a,"autonavvisibility",this.SS);this.J.L("web_autonav_color_transition")&&(this.T(a,"autonavchange",this.I1),this.T(a,"onAutonavCoundownStarted",this.l8))},k6=function(a){var b=a.J.Vk(!0,a.J.isFullscreen());
g.Nu(a.container.element,"ytp-autonav-endscreen-small-mode",a.Nf(b));g.Nu(a.container.element,"ytp-autonav-endscreen-is-premium",!!a.suggestion&&!!a.suggestion.FK);g.Nu(a.J.getRootNode(),"ytp-autonav-endscreen-cancelled-state",!a.J.Bf());g.Nu(a.J.getRootNode(),"countdown-running",a.al());g.Nu(a.container.element,"ytp-player-content",a.J.Bf());g.Yr(a.overlay.element,{width:b.width+"px"});if(!a.al()){a.J.Bf()?vob(a,Math.round(wob(a)/1E3)):vob(a);b=!!a.suggestion&&!!a.suggestion.Is;var c=a.J.Bf()||!b;
g.Nu(a.container.element,"ytp-autonav-endscreen-upnext-alternative-header-only",!c&&b);g.Nu(a.container.element,"ytp-autonav-endscreen-upnext-no-alternative-header",c&&!b);g.jG(a.B,a.J.Bf());g.Nu(a.element,"ytp-enable-w2w-color-transitions",xob(a))}},uob=function(a){var b=wob(a),c=Math,d=c.min;
var e=a.C?Date.now()-a.C:0;c=d.call(c,e,b);vob(a,Math.ceil((b-c)/1E3));500>=b-c&&a.al()?a.select(!0):a.al()&&a.D.start()},wob=function(a){if(a.J.isFullscreen()){var b;
a=null==(b=a.J.getVideoData())?void 0:b.QB;return-1===a||void 0===a?8E3:a}return 0<=a.J.Zs()?a.J.Zs():g.zJ(a.J.U().experiments,"autoplay_time")||1E4},tob=function(a,b){a.J.L("web_player_autonav_next_button_renderer");
b=b.n5;a.K=null==b?void 0:b.navigationEndpoint;b=null==b?void 0:b.trackingParams;a.playButton&&b&&a.J.hg(a.playButton.element,b)},xob=function(a){var b;
return!(null==(b=a.J.getVideoData())||!b.watchToWatchTransitionRenderer)},vob=function(a,b){b=void 0===b?-1:b;
a=a.j.Ga("ytp-autonav-endscreen-upnext-header");g.yf(a);if(0<=b){b=String(b);var c="Up next in $SECONDS".match(RegExp("\\$SECONDS","gi"))[0],d="Up next in $SECONDS".indexOf(c);if(0<=d){a.appendChild(g.wf("Up next in $SECONDS".slice(0,d)));var e=g.vf("span");g.Hu(e,"ytp-autonav-endscreen-upnext-header-countdown-number");g.Gf(e,b);a.appendChild(e);a.appendChild(g.wf("Up next in $SECONDS".slice(d+c.length)));return}}g.Gf(a,"Up next")},l6=function(a,b){g.U.call(this,{I:"div",
Ma:["html5-endscreen","ytp-player-content",b||"base-endscreen"]});this.created=!1;this.player=a},m6=function(a){g.U.call(this,{I:"div",
Ma:["ytp-upnext","ytp-player-content"],W:{"aria-label":"{{aria_label}}"},V:[{I:"div",S:"ytp-cued-thumbnail-overlay-image",W:{style:"{{background}}"}},{I:"span",S:"ytp-upnext-top",V:[{I:"span",S:"ytp-upnext-header",xa:"Up Next"},{I:"span",S:"ytp-upnext-title",xa:"{{title}}"},{I:"span",S:"ytp-upnext-author",xa:"{{author}}"}]},{I:"a",S:"ytp-upnext-autoplay-icon",W:{role:"button",href:"{{url}}","aria-label":"Play next video"},V:[{I:"svg",W:{height:"100%",version:"1.1",viewBox:"0 0 72 72",width:"100%"},
V:[{I:"circle",S:"ytp-svg-autoplay-circle",W:{cx:"36",cy:"36",fill:"#fff","fill-opacity":"0.3",r:"31.5"}},{I:"circle",S:"ytp-svg-autoplay-ring",W:{cx:"-36",cy:"36","fill-opacity":"0",r:"33.5",stroke:"#FFFFFF","stroke-dasharray":"211","stroke-dashoffset":"-211","stroke-width":"4",transform:"rotate(-90)"}},{I:"path",S:"ytp-svg-fill",W:{d:"M 24,48 41,36 24,24 V 48 z M 44,24 v 24 h 4 V 24 h -4 z"}}]}]},{I:"span",S:"ytp-upnext-bottom",V:[{I:"span",S:"ytp-upnext-cancel"},{I:"span",S:"ytp-upnext-paused",
xa:"Autoplay is paused"}]}]});this.api=a;this.cancelButton=null;this.G=this.Ga("ytp-svg-autoplay-ring");this.C=this.notification=this.j=this.suggestion=null;this.D=new g.Bu(this.gH,5E3,this);this.B=0;var b=this.Ga("ytp-upnext-cancel");this.cancelButton=new g.U({I:"button",Ma:["ytp-upnext-cancel-button","ytp-button"],W:{tabindex:"0","aria-label":"Cancel autoplay"},xa:"Cancel"});g.L(this,this.cancelButton);this.cancelButton.Ta("click",this.K1,this);this.cancelButton.Ea(b);this.cancelButton&&this.api.xb(this.cancelButton.element,
this,115129);g.L(this,this.D);this.api.xb(this.element,this,18788);b=this.Ga("ytp-upnext-autoplay-icon");this.T(b,"click",this.L1);this.api.xb(b,this,115130);this.VS();this.T(a,"autonavvisibility",this.VS);this.T(a,"mdxnowautoplaying",this.X8);this.T(a,"mdxautoplaycanceled",this.Y8);g.Nu(this.element,"ytp-upnext-mobile",this.api.U().B)},yob=function(a,b){if(b)return b;
if(a.api.isFullscreen()){var c;a=null==(c=a.api.getVideoData())?void 0:c.QB;return-1===a||void 0===a?8E3:a}return 0<=a.api.Zs()?a.api.Zs():g.zJ(a.api.U().experiments,"autoplay_time")||1E4},zob=function(a,b){b=yob(a,b);
var c=Math,d=c.min;var e=(0,g.FD)()-a.B;c=d.call(c,e,b);b=0===b?1:Math.min(c/b,1);a.G.setAttribute("stroke-dashoffset",""+-211*(b+1));1<=b&&a.al()&&3!==a.api.getPresentingPlayerType()?a.select(!0):a.al()&&a.j.start()},n6=function(a){l6.call(this,a,"autonav-endscreen");
this.overlay=this.videoData=null;this.table=new g.U({I:"div",S:"ytp-suggestion-panel",V:[{I:"div",Ma:["ytp-autonav-endscreen-upnext-header","ytp-autonav-endscreen-more-videos"],xa:"More videos"}]});this.N=new g.U({I:"div",S:"ytp-suggestions-container"});this.videos=[];this.C=null;this.G=this.K=!1;this.B=new j6(this.player);g.L(this,this.B);this.B.Ea(this.element);a.getVideoData().Tf?this.j=this.B:(this.j=new m6(a),g.tU(this.player,this.j.element,4),g.L(this,this.j));this.overlay=new g.U({I:"div",
S:"ytp-autonav-overlay-cancelled-state"});g.L(this,this.overlay);this.overlay.Ea(this.element);this.D=new g.PK(this);g.L(this,this.D);g.L(this,this.table);this.table.Ea(this.element);this.table.show();g.L(this,this.N);this.N.Ea(this.table.element);this.hide()},o6=function(a){var b=a.Bf();
b!==a.G&&(a.G=b,a.player.oa("autonavvisibility"),a.G?(a.B!==a.j&&a.B.hide(),a.table.hide()):(a.B!==a.j&&a.B.show(),a.table.show()))},p6=function(a,b){g.U.call(this,{I:"button",
Ma:["ytp-watch-on-youtube-button","ytp-button"],xa:"{{content}}"});this.J=a;this.buttonType=this.buttonType=b;this.i_();2===this.buttonType&&g.Ju(this.element,"ytp-continue-watching-button");this.Ta("click",this.onClick);this.Ta("videodatachange",this.i_);g.jG(this,!0)},q6=function(a,b){l6.call(this,a,"embeds-lite-endscreen");
this.J=a;this.wb=b;this.J.xb(this.element,this,156943);this.watchButton=new p6(a,2);g.L(this,this.watchButton);this.watchButton.Ea(this.element);this.hide()},Aob=function(a){l6.call(this,a,"subscribecard-endscreen");
this.j=new g.U({I:"div",S:"ytp-subscribe-card",V:[{I:"img",S:"ytp-author-image",W:{src:"{{profilePicture}}"}},{I:"div",S:"ytp-subscribe-card-right",V:[{I:"div",S:"ytp-author-name",xa:"{{author}}"},{I:"div",S:"html5-subscribe-button-container"}]}]});g.L(this,this.j);this.j.Ea(this.element);var b=a.getVideoData();this.subscribeButton=new g.kW("Subscribe",null,"Unsubscribe",null,!0,!1,b.Ml,b.subscribed,"trailer-endscreen",null,a);g.L(this,this.subscribeButton);this.subscribeButton.Ea(this.j.Ga("html5-subscribe-button-container"));
this.T(a,"videodatachange",this.Ra);this.Ra();this.hide()},r6=function(a){var b=a.U(),c=g.iL||g.$R?{style:"will-change: opacity"}:void 0,d=b.D,e=["ytp-videowall-still"];
b.B&&e.push("ytp-videowall-show-text");g.U.call(this,{I:"a",Ma:e,W:{href:"{{url}}",target:d?b.Y:"","aria-label":"{{aria_label}}","data-is-live":"{{is_live}}","data-is-list":"{{is_list}}","data-is-mix":"{{is_mix}}"},V:[{I:"div",S:"ytp-videowall-still-image",W:{style:"{{background}}"}},{I:"span",S:"ytp-videowall-still-info",W:{"aria-hidden":"true"},V:[{I:"span",S:"ytp-videowall-still-info-bg",V:[{I:"span",S:"ytp-videowall-still-info-content",W:c,V:[{I:"span",S:"ytp-videowall-still-info-title",xa:"{{title}}"},
{I:"span",S:"ytp-videowall-still-info-author",xa:"{{author_and_views}}"},{I:"span",S:"ytp-videowall-still-info-live",xa:"Live"},{I:"span",S:"ytp-videowall-still-info-duration",xa:"{{duration}}"}]}]}]},{I:"span",Ma:["ytp-videowall-still-listlabel-regular","ytp-videowall-still-listlabel"],W:{"aria-hidden":"true"},V:[{I:"span",S:"ytp-videowall-still-listlabel-icon"},"Playlist",{I:"span",S:"ytp-videowall-still-listlabel-length",V:[" (",{I:"span",xa:"{{playlist_length}}"},")"]}]},{I:"span",Ma:["ytp-videowall-still-listlabel-mix",
"ytp-videowall-still-listlabel"],W:{"aria-hidden":"true"},V:[{I:"span",S:"ytp-videowall-still-listlabel-mix-icon"},"Mix",{I:"span",S:"ytp-videowall-still-listlabel-length",xa:" (50+)"}]}]});this.suggestion=null;this.B=d;this.api=a;this.j=new g.PK(this);g.L(this,this.j);this.Ta("click",this.onClick);this.Ta("keypress",this.onKeyPress);this.j.T(a,"videodatachange",this.onVideoDataChange);a.ag(this.element,this);this.onVideoDataChange()},s6=function(a){l6.call(this,a,"videowall-endscreen");
var b=this;this.J=a;this.C=0;this.stills=[];this.D=this.videoData=null;this.G=this.N=!1;this.Y=null;this.B=new g.PK(this);g.L(this,this.B);this.K=new g.Bu(function(){g.Ju(b.element,"ytp-show-tiles")},0);
g.L(this,this.K);var c=new g.U({I:"button",Ma:["ytp-button","ytp-endscreen-previous"],W:{"aria-label":"Previous"},V:[g.pG()]});g.L(this,c);c.Ea(this.element);c.Ta("click",this.P1,this);this.table=new g.gG({I:"div",S:"ytp-endscreen-content"});g.L(this,this.table);this.table.Ea(this.element);c=new g.U({I:"button",Ma:["ytp-button","ytp-endscreen-next"],W:{"aria-label":"Next"},V:[g.qG()]});g.L(this,c);c.Ea(this.element);c.Ta("click",this.O1,this);a.getVideoData().Tf?this.j=new j6(a,!0):this.j=new m6(a);
g.L(this,this.j);g.tU(this.player,this.j.element,4);a.xb(this.element,this,158789);this.hide()},t6=function(a){return g.uU(a.player)&&a.BC()&&!a.D},u6=function(a){var b=a.Bf();
b!==a.N&&(a.N=b,a.player.oa("autonavvisibility"))},v6=function(a){l6.call(this,a,"watch-again-on-youtube-endscreen");
this.watchButton=new p6(a,1);g.L(this,this.watchButton);this.watchButton.Ea(this.element);g.Ocb(a)&&(this.j=new g.s2(a,g.dU(a)),g.L(this,this.j),this.B=new g.U({I:"div",Ma:["ytp-watch-again-on-youtube-endscreen-more-videos-container"],W:{tabIndex:"-1"},V:[this.j]}),g.L(this,this.B),this.j.Ea(this.B.element),this.B.Ea(this.element));a.xb(this.element,this,156914);this.hide()},Eob=function(a){g.zV.call(this,a);
var b=this;this.endScreen=null;this.B=this.j=this.C=this.D=!1;this.listeners=new g.PK(this);g.L(this,this.listeners);var c=a.U(),d=a.getVideoData();d=d&&0!==d.limitedPlaybackDurationInSeconds;g.FC(g.jS(c))&&d&&!g.pU(a)?(this.B=!0,this.endScreen=new q6(a,g.dU(a))):g.qU(a)?this.endScreen=new v6(a):Bob(a)?(this.D=!0,Cob(this),this.j?this.endScreen=new n6(a):this.endScreen=new s6(a)):c.Zg?this.endScreen=new Aob(a):this.endScreen=new l6(a);g.L(this,this.endScreen);g.tU(a,this.endScreen.element,4);Dob(this);
this.listeners.T(a,"videodatachange",this.onVideoDataChange,this);this.listeners.T(a,g.fK("endscreen"),function(e){b.onCueRangeEnter(e)});
this.listeners.T(a,g.gK("endscreen"),function(e){b.onCueRangeExit(e)})},Cob=function(a){var b=a.player.getVideoData();
if(!b||a.j===b.Pl&&a.C===b.Tf)return!1;a.j=b.Pl;a.C=b.Tf;return!0},Bob=function(a){a=a.U();
return a.Jd&&!a.Zg},Dob=function(a){a.player.lf("endscreen");
var b=a.player.getVideoData();b=new g.eK(Math.max(1E3*(b.lengthSeconds-10),0),0x8000000000000,{id:"preload",namespace:"endscreen"});var c=new g.eK(0x8000000000000,0x8000000000000,{id:"load",priority:8,namespace:"endscreen"});a.player.xf([b,c])};
g.lU.prototype.Zs=g.ca(16,function(){return this.app.Zs()});
g.U0.prototype.Zs=g.ca(15,function(){return this.getVideoData().HU});
g.WT.prototype.Gm=g.ca(14,function(a){this.Mh().Gm(a)});
g.JW.prototype.Gm=g.ca(13,function(a){this.j!==a&&(this.j=a,this.Ra())});
g.VX.prototype.Gm=g.ca(12,function(a){this.overflowButton&&this.overflowButton.Gm(a)});
g.WT.prototype.Hm=g.ca(11,function(a){this.Mh().Hm(a)});
g.OW.prototype.Hm=g.ca(10,function(a){this.j!==a&&(this.j=a,this.Ra())});
g.VX.prototype.Hm=g.ca(9,function(a){this.shareButton&&this.shareButton.Hm(a)});
g.WT.prototype.pu=g.ca(8,function(a){this.Mh().pu(a)});
g.cW.prototype.pu=g.ca(7,function(a){this.GQ!==a&&(this.GQ=a,this.qq())});
g.WT.prototype.Qr=g.ca(6,function(a){this.Mh().Qr(a)});
g.VX.prototype.Qr=g.ca(5,function(a){this.FQ!==a&&(this.FQ=a,this.Hk())});g.w(i6,g.U);i6.prototype.select=function(){this.J.Jo(this.suggestion.videoId,this.suggestion.sessionData,this.suggestion.playlistId,void 0,void 0,this.suggestion.YC||void 0)&&this.J.rb(this.element)};
i6.prototype.onClick=function(a){g.JU(a,this.J,this.j,this.suggestion.sessionData||void 0)&&this.select()};
i6.prototype.onKeyPress=function(a){switch(a.keyCode){case 13:case 32:a.defaultPrevented||(this.select(),a.preventDefault())}};g.w(j6,g.U);g.k=j6.prototype;g.k.pG=function(a){this.suggestion!==a&&(this.suggestion=a,h6(this.j,a),this.playButton.updateValue("url",this.suggestion.Wk()),k6(this))};
g.k.al=function(){return 0<this.C};
g.k.sB=function(){this.al()||(this.C=Date.now(),uob(this),sob(this.J,wob(this)),g.Nu(this.J.getRootNode(),"countdown-running",this.al()))};
g.k.Ow=function(){this.iq();uob(this);var a=this.j.Ga("ytp-autonav-endscreen-upnext-header");a&&g.Gf(a,"Up next")};
g.k.iq=function(){this.al()&&(this.D.stop(),this.C=0)};
g.k.select=function(a){this.J.nextVideo(!1,void 0===a?!1:a);this.iq()};
g.k.US=function(a){g.JU(a,this.J)&&(a.currentTarget===this.playButton.element?this.J.rb(this.playButton.element):a.currentTarget===this.j.Ga("ytp-autonav-endscreen-link-container")&&(a=this.j.Ga("ytp-autonav-endscreen-link-container"),this.J.Wa(a,!0),this.J.rb(a)),this.J.L("web_player_autonav_next_button_renderer")&&this.K?(this.J.Qa("innertubeCommand",this.K),this.iq()):this.select())};
g.k.J1=function(){this.J.rb(this.cancelButton.element);g.nU(this.J,!0);this.G&&this.J.Qa("innertubeCommand",this.G)};
g.k.onVideoDataChange=function(a,b){this.J.L("web_player_autonav_next_button_renderer")&&tob(this,b);var c;this.G=null==(c=b.e5)?void 0:c.command};
g.k.l8=function(a){if(xob(this)){var b=this.J.getVideoData().watchToWatchTransitionRenderer,c=null==b?void 0:b.fromColorPaletteDark;b=null==b?void 0:b.toColorPaletteDark;if(c&&b){var d=this.element;d.style.setProperty("--w2w-start-background-color",g.iH(c.surgeColor));d.style.setProperty("--w2w-start-primary-text-color",g.iH(c.primaryTitleColor));d.style.setProperty("--w2w-start-secondary-text-color",g.iH(c.secondaryTitleColor));d.style.setProperty("--w2w-end-background-color",g.iH(b.surgeColor));
d.style.setProperty("--w2w-end-primary-text-color",g.iH(b.primaryTitleColor));d.style.setProperty("--w2w-end-secondary-text-color",g.iH(b.secondaryTitleColor));d.style.setProperty("--w2w-animation-duration",a+"ms")}g.Nu(this.element,"ytp-w2w-animate",!0)}};
g.k.I1=function(a){this.J.L("web_autonav_color_transition")&&2!==a&&g.Nu(this.element,"ytp-w2w-animate",!1)};
g.k.SS=function(){var a=this.J.Bf();this.N&&this.Gb!==a&&g.jG(this,a);k6(this);this.J.Wa(this.container.element,a);this.J.Wa(this.cancelButton.element,a);this.J.Wa(this.j.Ga("ytp-autonav-endscreen-link-container"),a);this.J.Wa(this.playButton.element,a)};
g.k.Nf=function(a){return 400>a.width||459>a.height};g.w(l6,g.U);g.k=l6.prototype;g.k.create=function(){this.created=!0};
g.k.destroy=function(){this.created=!1};
g.k.BC=function(){return!1};
g.k.Bf=function(){return!1};
g.k.DX=function(){return!1};g.w(m6,g.U);g.k=m6.prototype;g.k.gH=function(){this.notification&&(this.D.stop(),this.Qc(this.C),this.C=null,this.notification.close(),this.notification=null)};
g.k.pG=function(a){this.suggestion=a;h6(this,a,"hqdefault.jpg")};
g.k.VS=function(){g.jG(this,this.api.Bf());this.api.Wa(this.element,this.api.Bf());this.api.Wa(this.Ga("ytp-upnext-autoplay-icon"),this.api.Bf());this.cancelButton&&this.api.Wa(this.cancelButton.element,this.api.Bf())};
g.k.g9=function(){window.focus();this.gH()};
g.k.sB=function(a){var b=this;this.al()||(g.OE("a11y-announce","Up Next "+this.suggestion.title),this.B=(0,g.FD)(),this.j=new g.Bu(function(){zob(b,a)},25),zob(this,a),sob(this.api,yob(this,a)));
g.Lu(this.element,"ytp-upnext-autoplay-paused")};
g.k.hide=function(){g.U.prototype.hide.call(this)};
g.k.al=function(){return!!this.j};
g.k.Ow=function(){this.iq();this.B=(0,g.FD)();zob(this);g.Ju(this.element,"ytp-upnext-autoplay-paused")};
g.k.iq=function(){this.al()&&(this.j.dispose(),this.j=null)};
g.k.select=function(a){a=void 0===a?!1:a;if(this.api.U().L("autonav_notifications")&&a&&window.Notification&&"function"===typeof document.hasFocus){var b=Notification.permission;"default"===b?Notification.requestPermission():"granted"!==b||document.hasFocus()||(this.gH(),this.notification=new Notification("Up Next",{body:this.suggestion.title,icon:this.suggestion.Vg()}),this.C=this.T(this.notification,"click",this.g9),this.D.start())}this.iq();this.api.nextVideo(!1,a)};
g.k.L1=function(a){!g.Ff(this.cancelButton.element,a.target)&&g.JU(a,this.api)&&(this.api.Bf()&&this.api.rb(this.Ga("ytp-upnext-autoplay-icon")),this.select())};
g.k.K1=function(){this.api.Bf()&&this.cancelButton&&this.api.rb(this.cancelButton.element);g.nU(this.api,!0)};
g.k.X8=function(a){this.api.getPresentingPlayerType();this.show();this.sB(a)};
g.k.Y8=function(){this.api.getPresentingPlayerType();this.iq();this.hide()};
g.k.ya=function(){this.iq();this.gH();g.U.prototype.ya.call(this)};g.w(n6,l6);g.k=n6.prototype;g.k.create=function(){l6.prototype.create.call(this);this.D.T(this.player,"appresize",this.VB);this.D.T(this.player,"onVideoAreaChange",this.VB);this.D.T(this.player,"videodatachange",this.onVideoDataChange);this.D.T(this.player,"autonavchange",this.WS);this.D.T(this.player,"onAutonavCancelled",this.M1);this.onVideoDataChange()};
g.k.show=function(){l6.prototype.show.call(this);(this.K||this.C&&this.C!==this.videoData.clientPlaybackNonce)&&g.nU(this.player,!1);g.uU(this.player)&&this.BC()&&!this.C?(o6(this),2===this.videoData.autonavState?3===this.player.getVisibilityState()?this.j.select(!0):this.j.sB():3===this.videoData.autonavState&&this.j.Ow()):(g.nU(this.player,!0),o6(this));this.VB()};
g.k.hide=function(){l6.prototype.hide.call(this);this.j.Ow();o6(this)};
g.k.VB=function(){var a=this.player.Vk(!0,this.player.isFullscreen());o6(this);k6(this.B);g.Nu(this.element,"ytp-autonav-cancelled-small-mode",this.Nf(a));g.Nu(this.element,"ytp-autonav-cancelled-tiny-mode",this.II(a));g.Nu(this.element,"ytp-autonav-cancelled-mini-mode",400>=a.width||360>=a.height);this.overlay&&g.Yr(this.overlay.element,{width:a.width+"px"});if(!this.G)for(a=0;a<this.videos.length;a++)g.Nu(this.videos[a].element,"ytp-suggestion-card-with-margin",1===a%2)};
g.k.onVideoDataChange=function(){var a=this.player.getVideoData();if(this.videoData!==a&&a){this.videoData=a;if((a=this.videoData.suggestions)&&a.length||this.player.L("web_player_autonav_empty_suggestions_fix")){var b=g.pT(this.videoData);b&&(this.j.pG(b),this.j!==this.B&&this.B.pG(b))}if(a&&a.length)for(b=0;b<Fob.length;++b){var c=Fob[b];if(a&&a[c]){this.videos[b]=new i6(this.player);var d=this.videos[b];c=a[c];d.suggestion!==c&&(d.suggestion=c,h6(d,c));g.L(this,this.videos[b]);this.videos[b].Ea(this.N.element)}}this.VB()}};
g.k.WS=function(a){1===a?(this.K=!1,this.C=this.videoData.clientPlaybackNonce,this.j.iq(),this.Gb&&this.VB()):(this.K=!0,this.Bf()&&(2===a?this.j.sB():3===a&&this.j.Ow()))};
g.k.M1=function(a){a?this.WS(1):(this.C=null,this.K=!1)};
g.k.BC=function(){return 1!==this.videoData.autonavState};
g.k.Nf=function(a){return(910>a.width||459>a.height)&&!this.II(a)&&!(400>=a.width||360>=a.height)};
g.k.II=function(a){return 800>a.width&&!(400>=a.width||360>=a.height)};
g.k.Bf=function(){return this.Gb&&g.uU(this.player)&&this.BC()&&!this.C};
var Fob=[1,3,2,4];g.w(p6,g.U);g.k=p6.prototype;g.k.i_=function(){switch(this.buttonType){case 1:var a="Watch again on YouTube";var b=156915;break;case 2:a="Continue watching on YouTube";b=156942;break;default:a="Continue watching on YouTube",b=156942}this.update({content:a});this.J.gk(this.element)&&this.J.OC(this.element);this.J.xb(this.element,this,b)};
g.k.onClick=function(a){this.J.L("web_player_log_click_before_generating_ve_conversion_params")&&this.J.rb(this.element);g.KU(this.getVideoUrl(),this.J,a);this.J.L("web_player_log_click_before_generating_ve_conversion_params")||this.J.rb(this.element)};
g.k.getVideoUrl=function(){var a=!0;switch(this.buttonType){case 1:a=!0;break;case 2:a=!1}a=this.J.getVideoUrl(a,!1,!1,!0);var b=this.J.U();if(g.aS(b)||g.iS(b)){var c={};g.aS(b)&&g.aU(this.J,"addEmbedsConversionTrackingParams",[c]);a:{switch(this.buttonType){case 2:b="emb_ytp_continue_watching";break a}b="emb_ytp_watch_again"}g.AP(c,b);a=g.Jl(a,c)}return a};
g.k.Wa=function(){this.J.Wa(this.element,this.Gb&&this.Z)};
g.k.show=function(){g.U.prototype.show.call(this);this.Wa()};
g.k.hide=function(){g.U.prototype.hide.call(this);this.Wa()};
g.k.kc=function(a){g.U.prototype.kc.call(this,a);this.Wa()};g.w(q6,l6);q6.prototype.show=function(){3!==this.player.getPlayerState()&&(l6.prototype.show.call(this),this.wb.Qr(!0),this.wb.Hm(!0),this.J.U().Td||this.wb.Gm(!0),this.J.Wa(this.element,!0),this.watchButton.kc(!0))};
q6.prototype.hide=function(){l6.prototype.hide.call(this);this.wb.Qr(!1);this.wb.Hm(!1);this.wb.Gm(!1);this.J.Wa(this.element,!1);this.watchButton.kc(!1)};g.w(Aob,l6);Aob.prototype.Ra=function(){var a=this.player.getVideoData();this.j.update({profilePicture:a.profilePicture,author:a.author});this.subscribeButton.channelId=a.Ml;var b=this.subscribeButton;a.subscribed?b.j():b.B()};g.w(r6,g.U);r6.prototype.select=function(){this.api.Jo(this.suggestion.videoId,this.suggestion.sessionData,this.suggestion.playlistId,void 0,void 0,this.suggestion.YC||void 0)&&this.api.rb(this.element)};
r6.prototype.onClick=function(a){if(g.aS(this.api.U())&&this.api.L("web_player_log_click_before_generating_ve_conversion_params")){this.api.rb(this.element);var b=this.suggestion.Wk(),c={};g.uSa(this.api,c,"emb_rel_end");b=g.Jl(b,c);g.KU(b,this.api,a)}else g.JU(a,this.api,this.B,this.suggestion.sessionData||void 0)&&this.select()};
r6.prototype.onKeyPress=function(a){switch(a.keyCode){case 13:case 32:a.defaultPrevented||(this.select(),a.preventDefault())}};
r6.prototype.onVideoDataChange=function(){var a=this.api.getVideoData(),b=this.api.U();this.B=a.Pd?!1:b.D};g.w(s6,l6);g.k=s6.prototype;g.k.create=function(){l6.prototype.create.call(this);var a=this.player.getVideoData();a&&(this.videoData=a);this.uq();this.B.T(this.player,"appresize",this.uq);this.B.T(this.player,"onVideoAreaChange",this.uq);this.B.T(this.player,"videodatachange",this.onVideoDataChange);this.B.T(this.player,"autonavchange",this.vL);this.B.T(this.player,"onAutonavCancelled",this.N1);a=this.videoData.autonavState;a!==this.Y&&this.vL(a);this.B.T(this.element,"transitionend",this.v$)};
g.k.destroy=function(){g.UC(this.B);g.vb(this.stills);this.stills=[];l6.prototype.destroy.call(this);g.Lu(this.element,"ytp-show-tiles");this.K.stop();this.Y=this.videoData.autonavState};
g.k.BC=function(){return 1!==this.videoData.autonavState};
g.k.show=function(){var a=this.Gb;l6.prototype.show.call(this);g.Lu(this.element,"ytp-show-tiles");this.player.U().B?g.Du(this.K):this.K.start();(this.G||this.D&&this.D!==this.videoData.clientPlaybackNonce)&&g.nU(this.player,!1);t6(this)?(u6(this),2===this.videoData.autonavState?3===this.player.getVisibilityState()?this.j.select(!0):this.j.sB():3===this.videoData.autonavState&&this.j.Ow()):(g.nU(this.player,!0),u6(this));a!==this.Gb&&this.player.Wa(this.element,!0)};
g.k.hide=function(){var a=this.Gb;l6.prototype.hide.call(this);this.j.Ow();u6(this);a!==this.Gb&&this.player.Wa(this.element,!1)};
g.k.v$=function(a){a.target===this.element&&this.uq()};
g.k.uq=function(){var a,b,c,d;var e=(null==(a=this.videoData)?0:null==(b=a.suggestions)?0:b.length)?null==(c=this.videoData)?void 0:c.suggestions:[null==(d=this.videoData)?void 0:g.pT(d)];if(e.length){g.Ju(this.element,"ytp-endscreen-paginate");var f=this.J.Vk(!0,this.J.isFullscreen());if(a=g.dU(this.J))a=a.dg()?48:32,f.width-=2*a;var h=f.width/f.height;d=96/54;b=a=2;var l=Math.max(f.width/96,2),m=Math.max(f.height/54,2);c=e.length;var n=Math.pow(2,2);var p=c*n+(Math.pow(2,2)-n);p+=Math.pow(2,2)-
n;for(p-=n;0<p&&(a<l||b<m);){var q=a/2,r=b/2,t=a<=l-2&&p>=r*n,u=b<=m-2&&p>=q*n;if((q+1)/r*d/h>h/(q/(r+1)*d)&&u)p-=q*n,b+=2;else if(t)p-=r*n,a+=2;else if(u)p-=q*n,b+=2;else break}d=!1;p>=3*n&&6>=c*n-p&&(4<=b||4<=a)&&(d=!0);n=96*a;p=54*b;h=n/p<h?f.height/p:f.width/n;h=Math.min(h,2);n=Math.floor(Math.min(f.width,n*h));p=Math.floor(Math.min(f.height,p*h));f=this.table.element;f.ariaLive="polite";g.hs(f,n,p);g.Yr(f,{marginLeft:n/-2+"px",marginTop:p/-2+"px"});this.j.pG(g.pT(this.videoData));this.j instanceof
j6&&k6(this.j);g.Nu(this.element,"ytp-endscreen-takeover",t6(this));u6(this);n+=4;p+=4;h=0;f.ariaBusy="true";for(l=0;l<a;l++)for(m=0;m<b;m++)if(q=h,t=0,d&&l>=a-2&&m>=b-2?t=1:0===m%2&&0===l%2&&(2>m&&2>l?0===m&&0===l&&(t=2):t=2),q=g.se(q+this.C,c),0!==t){r=this.stills[h];r||(r=new r6(this.player),this.stills[h]=r,f.appendChild(r.element));u=Math.floor(p*m/b);var x=Math.floor(n*l/a),B=Math.floor(p*(m+t)/b)-u-4,F=Math.floor(n*(l+t)/a)-x-4;g.ds(r.element,x,u);g.hs(r.element,F,B);g.Yr(r.element,"transitionDelay",
(m+l)/20+"s");g.Nu(r.element,"ytp-videowall-still-mini",1===t);g.Nu(r.element,"ytp-videowall-still-large",2<t);t=Math.max(F,B);g.Nu(r.element,"ytp-videowall-still-round-large",256<=t);g.Nu(r.element,"ytp-videowall-still-round-medium",96<t&&256>t);g.Nu(r.element,"ytp-videowall-still-round-small",96>=t);q=e[q];r.suggestion!==q&&(r.suggestion=q,t=r.api.U(),u=g.Iu(r.element,"ytp-videowall-still-large")?"hqdefault.jpg":"mqdefault.jpg",h6(r,q,u),g.aS(t)&&!r.api.L("web_player_log_click_before_generating_ve_conversion_params")&&
(t=q.Wk(),u={},g.aU(r.api,"addEmbedsConversionTrackingParams",[u]),t=g.Jl(t,g.AP(u,"emb_rel_end")),r.updateValue("url",t)),(q=(q=q.sessionData)&&q.itct)&&r.api.hg(r.element,q));h++}f.ariaBusy="false";g.Nu(this.element,"ytp-endscreen-paginate",h<c);for(e=this.stills.length-1;e>=h;e--)a=this.stills[e],g.Af(a.element),g.ub(a);this.stills.length=h}};
g.k.onVideoDataChange=function(){var a=this.player.getVideoData();this.videoData!==a&&(this.C=0,this.videoData=a,this.uq())};
g.k.O1=function(){this.C+=this.stills.length;this.uq()};
g.k.P1=function(){this.C-=this.stills.length;this.uq()};
g.k.DX=function(){return this.j.al()};
g.k.vL=function(a){1===a?(this.G=!1,this.D=this.videoData.clientPlaybackNonce,this.j.iq(),this.Gb&&this.uq()):(this.G=!0,this.Gb&&t6(this)&&(2===a?this.j.sB():3===a&&this.j.Ow()))};
g.k.N1=function(a){if(a){for(a=0;a<this.stills.length;a++)this.J.Wa(this.stills[a].element,!0);this.vL(1)}else this.D=null,this.G=!1;this.uq()};
g.k.Bf=function(){return this.Gb&&t6(this)};g.w(v6,l6);v6.prototype.MD=function(){var a;return null==(a=this.j)?void 0:a.MD()};
v6.prototype.show=function(){if(3!==this.player.getPlayerState()){l6.prototype.show.call(this);var a=this.B;if(a){var b=this.j.MD();g.Nu(this.element,"ytp-shorts-branded-ui",b);b?a.show():a.hide()}var c;null==(c=g.dU(this.player))||c.pu(!0);this.player.Wa(this.element,!0);this.watchButton.kc(!0)}};
v6.prototype.hide=function(){l6.prototype.hide.call(this);var a;null==(a=g.dU(this.player))||a.pu(!1);this.player.Wa(this.element,!1);this.watchButton.kc(!1)};g.w(Eob,g.zV);g.k=Eob.prototype;g.k.wu=function(){var a=this.player.getVideoData(),b=a.mutedAutoplay;if((g.qU(this.player)||this.B)&&!b)return!0;var c;var d=!!((null==a?0:g.pT(a))||(null==a?0:null==(c=a.suggestions)?0:c.length));d=!Bob(this.player)||d;a=a.wj||g.iS(a.Ia);c=this.player.mD();return d&&!a&&!c&&!b};
g.k.Bf=function(){return this.endScreen.Bf()};
g.k.e7=function(){return this.Bf()?this.endScreen.DX():!1};
g.k.ya=function(){this.player.lf("endscreen");g.zV.prototype.ya.call(this)};
g.k.load=function(){var a=this.player.getVideoData();var b=a.transitionEndpointAtEndOfStream;if(b&&b.videoId){var c=this.player.Eb().Re.get("heartbeat"),d=g.pT(a);!d||b.videoId!==d.videoId||a.MS?(this.player.Jo(b.videoId,void 0,void 0,!0,!0,b),c&&c.SI("HEARTBEAT_ACTION_TRIGGER_AT_STREAM_END","HEARTBEAT_ACTION_TRANSITION_REASON_HAS_NEW_STREAM_TRANSITION_ENDPOINT"),a=!0):a=!1}else a=!1;a||(g.zV.prototype.load.call(this),this.endScreen.show())};
g.k.unload=function(){g.zV.prototype.unload.call(this);this.endScreen.hide();this.endScreen.destroy()};
g.k.onCueRangeEnter=function(a){this.wu()&&(this.endScreen.created||this.endScreen.create(),"load"===a.getId()&&this.load())};
g.k.onCueRangeExit=function(a){"load"===a.getId()&&this.loaded&&this.unload()};
g.k.onVideoDataChange=function(){Dob(this);this.D&&Cob(this)&&(this.endScreen&&(this.endScreen.hide(),this.endScreen.created&&this.endScreen.destroy(),this.endScreen.dispose()),this.j?this.endScreen=new n6(this.player):this.endScreen=new s6(this.player),g.L(this,this.endScreen),g.tU(this.player,this.endScreen.element,4))};g.yV("endscreen",Eob);})(_yt_player);
