(function(g){var window=this;'use strict';var Gob=function(a,b){if(!Number.isFinite(a))return String(a);a=String(a);var c=a.indexOf(".");-1===c&&(c=a.length);var d="-"===a[0]?"-":"";d&&(a=a.substring(1));return d+(0,g.sdb)("0",Math.max(0,b-c))+a},Hob=function(){return{I:"svg",
W:{fill:"#fff",height:"24px",viewBox:"0 0 24 24",width:"24px"},V:[{I:"path",W:{d:"M12 22c1.1 0 2-.9 2-2h-4c0 1.1.9 2 2 2zm6-6v-5c0-3.07-1.64-5.64-4.5-6.32V4c0-.83-.67-1.5-1.5-1.5s-1.5.67-1.5 1.5v.68C7.63 5.36 6 7.92 6 11v5l-2 2v1h16v-1l-2-2z"}}]}},Iob=function(){return{I:"svg",
W:{fill:"#fff",height:"24px",viewBox:"0 0 24 24",width:"24px"},V:[{I:"path",W:{d:"M12 22c1.1 0 2-.9 2-2h-4c0 1.1.9 2 2 2zm6-6v-5c0-3.07-1.63-5.64-4.5-6.32V4c0-.83-.67-1.5-1.5-1.5s-1.5.67-1.5 1.5v.68C7.64 5.36 6 7.92 6 11v5l-2 2v1h16v-1l-2-2zm-2 1H8v-6c0-2.48 1.51-4.5 4-4.5s4 2.02 4 4.5v6z"}}]}},Kob=function(a){"number"===typeof a?(this.date=Job(a,0,1),w6(this,1)):g.ab(a)?(this.date=Job(a.getFullYear(),a.getMonth(),a.getDate()),w6(this,a.getDate())):(this.date=new Date(g.lb()),a=this.date.getDate(),
this.date.setHours(0),this.date.setMinutes(0),this.date.setSeconds(0),this.date.setMilliseconds(0),w6(this,a))},Job=function(a,b,c){b=new Date(a,b,c);
0<=a&&100>a&&b.setFullYear(b.getFullYear()-1900);return b},w6=function(a,b){a.getDate()!=b&&a.date.setUTCHours(a.date.getUTCHours()+(a.getDate()<b?1:-1))},x6=function(a,b){g.xU.call(this,a,{I:"div",
S:"ytp-reminder-menu",W:{role:"menu",tabindex:"-1"},V:[{I:"div",S:"ytp-reminder-menu-contents",V:[{I:"div",S:"ytp-reminder-menu-items"}]}]},100,!0);this.buttonElement=b;this.j=[];this.menuPopupRenderer=void 0;this.items=this.Ga("ytp-reminder-menu-items");this.hide()},Mob=function(a){var b=Lob(a),c=0,d={};
for(c=0;c<b.length;d={HO:d.HO},c++){var e=a.j[c];e||(e=new g.U({I:"div",S:"ytp-reminder-menu-item",W:{role:"menuitem",tabindex:"0"},V:[{I:"div",S:"ytp-reminder-menu-item-icon",xa:"{{icon}}"},{I:"div",S:"ytp-reminder-menu-item-label",xa:"{{text}}"}]}),d.HO=c,e.Ta("click",function(l){return function(){var m=l.HO;a.Qb();m=Lob(a)[m];a.oa("reminderMenuItemClicked",m.serviceEndpoint||m.command)}}(d)),e.Ea(a.items),a.j[c]=e);
var f=b[c],h=null;switch(f.icon&&f.icon.iconType){case "NOTIFICATIONS":h=Hob();break;case "NOTIFICATIONS_NONE":h=Iob();break;case "NOTIFICATIONS_ACTIVE":h=g.uva()}f=f.text?g.nG(f.text):"";e.update({icon:h,text:f})}for(;c<a.j.length;)a.j.pop().dispose();0===c?a.Qb():a.xd(a.buttonElement)},Lob=function(a){return(a.menuPopupRenderer&&a.menuPopupRenderer.items||[]).reduce(function(b,c){c&&c.menuServiceItemRenderer&&b.push(c.menuServiceItemRenderer);
return b},[])},y6=function(a){g.U.call(this,{I:"div",
V:[{I:"button",Ma:["ytp-offline-slate-button","ytp-button"],V:[{I:"div",S:"ytp-offline-slate-button-icon",xa:"{{icon}}"},{I:"div",S:"ytp-offline-slate-button-text",xa:"{{text}}"}]}]});this.J=a;this.upcomingEventReminderButtonRenderer=this.toggleButtonRenderer=null;this.B=void 0;this.D=this.j=null;(this.buttonElement=this.Ga("ytp-offline-slate-button"))&&this.T(this.buttonElement,"click",this.G);this.hide()},Oob=function(a,b,c){!a.toggleButtonRenderer&&b&&b.toggleButtonRenderer?a.toggleButtonRenderer=
b.toggleButtonRenderer:b&&b.toggleButtonRenderer||(a.toggleButtonRenderer=null);
!a.upcomingEventReminderButtonRenderer&&c&&g.T(c,Nob)?a.upcomingEventReminderButtonRenderer=g.T(c,Nob):c&&g.T(c,Nob)||(a.upcomingEventReminderButtonRenderer=null);z6(a)},z6=function(a){if(a.toggleButtonRenderer){var b=a.toggleButtonRenderer;
if(b.isToggled){var c=b.toggledText?g.nG(b.toggledText):"";a.update({text:c,icon:Pob(b.toggledIcon)})}else c=b.defaultText?g.nG(b.defaultText):"",a.update({text:c,icon:Pob(b.defaultIcon)});a.show()}else a.upcomingEventReminderButtonRenderer?(b=Qob(a))?(c=b.text?g.nG(b.text):"",a.update({text:c,icon:Pob(b.icon)}),a.show()):a.hide():a.hide()},Sob=function(a,b,c){a.D||(a.D=new g.GE(a.J.U().zl));
var d={context:g.Wqa(a.D.config_||g.gE())};g.HF()&&(d.context.clientScreenNonce=g.HF());d.params=c;g.HE(a.D,b,d,{timeout:5E3,onSuccess:function(){a.upcomingEventReminderButtonRenderer&&a.B&&(a.upcomingEventReminderButtonRenderer.currentState=a.B,a.B=void 0)},
onError:function(){Rob(a)},
onTimeout:function(){Rob(a)}})},Rob=function(a){a.toggleButtonRenderer?(a.toggleButtonRenderer.isToggled=!a.toggleButtonRenderer.isToggled,z6(a)):a.upcomingEventReminderButtonRenderer&&(a.B=void 0,z6(a))},Pob=function(a){if(!a)return null;
switch(a.iconType){case "NOTIFICATIONS":return Hob();case "NOTIFICATIONS_NONE":return Iob();case "NOTIFICATIONS_ACTIVE":return g.uva();default:return null}},Qob=function(a){if(!a.upcomingEventReminderButtonRenderer)return null;
var b=a.B||a.upcomingEventReminderButtonRenderer.currentState;a=g.v(a.upcomingEventReminderButtonRenderer.states||[]);for(var c=a.next();!c.done;c=a.next())if((c=g.T(c.value,Tob))&&c.state===b&&c.button&&g.T(c.button,g.fN))return g.T(c.button,g.fN);return null},Uob=function(a){g.U.call(this,{I:"div",
S:"ytp-offline-slate",V:[{I:"div",S:"ytp-offline-slate-background"},{I:"div",S:"ytp-offline-slate-bar",V:[{I:"span",S:"ytp-offline-slate-icon",V:[{I:"svg",W:{fill:"#fff",height:"100%",viewBox:"0 0 24 24",width:"100%"},V:[{I:"path",W:{d:"M16.94 6.91l-1.41 1.45c.9.94 1.46 2.22 1.46 3.64s-.56 2.71-1.46 3.64l1.41 1.45c1.27-1.31 2.05-3.11 2.05-5.09s-.78-3.79-2.05-5.09zM19.77 4l-1.41 1.45C19.98 7.13 21 9.44 21 12.01c0 2.57-1.01 4.88-2.64 6.54l1.4 1.45c2.01-2.04 3.24-4.87 3.24-7.99 0-3.13-1.23-5.96-3.23-8.01zM7.06 6.91c-1.27 1.3-2.05 3.1-2.05 5.09s.78 3.79 2.05 5.09l1.41-1.45c-.9-.94-1.46-2.22-1.46-3.64s.56-2.71 1.46-3.64L7.06 6.91zM5.64 5.45L4.24 4C2.23 6.04 1 8.87 1 11.99c0 3.13 1.23 5.96 3.23 8.01l1.41-1.45C4.02 16.87 3 14.56 3 11.99s1.01-4.88 2.64-6.54z"}},
{I:"circle",W:{cx:"12",cy:"12",r:"3"}}]}]},{I:"span",S:"ytp-offline-slate-messages",V:[{I:"div",S:"ytp-offline-slate-main-text",W:{"aria-label":"{{label}}"},xa:"{{mainText}}"},{I:"div",S:"ytp-offline-slate-subtitle-text",xa:"{{subtitleText}}"}]},{I:"span",S:"ytp-offline-slate-buttons"}]},{I:"button",Ma:["ytp-offline-slate-close-button","ytp-button"],V:[g.qG()]},{I:"button",Ma:["ytp-offline-slate-open-button","ytp-button"],V:[g.pG()]}]});var b=this;this.api=a;this.j=this.B=null;this.background=this.Ga("ytp-offline-slate-background");
this.C=this.Ga("ytp-offline-slate-bar");this.G=new g.Bu(function(){g.Ju(b.C,"ytp-offline-slate-bar-fade")},15E3);
this.K=!1;this.D=new g.Bu(function(){g.Ju(b.element,"ytp-offline-slate-collapsed")},15E3);
g.L(this,this.D);g.L(this,this.G);this.countdownTimer=new g.Bu(this.f0,1E3,this);this.T(a,"presentingplayerstatechange",this.k0);this.T(a,"livestatedata",this.Ra);a=this.Ga("ytp-offline-slate-close-button");this.T(a,"click",function(){g.Ju(b.element,"ytp-offline-slate-collapsed")});
a=this.Ga("ytp-offline-slate-open-button");this.T(a,"click",function(){g.Lu(b.element,"ytp-offline-slate-collapsed")});
this.hide();a=this.getVideoData();a.getPlayerResponse()&&(a=a.getPlayerResponse().playabilityStatus)&&this.Ra(a);a=8===this.api.getPresentingPlayerType()&&!this.getVideoData().Ul;var c=8===this.api.getPresentingPlayerType();g.Nu(this.element,"ytp-offline-slate-premiere-trailer",a);g.Nu(this.element,"ytp-offline-slate-hide-background",c)},Vob=function(a,b,c){if(b){var d=null!=b.subtitleText?g.nG(b.subtitleText):"";
c=c?c:null!=b.mainText?g.nG(b.mainText):"";var e,f,h,l;b=null!=(l=null==(e=b.mainText)?void 0:null==(f=e.accessibility)?void 0:null==(h=f.accessibilityData)?void 0:h.label)?l:c;a.update({mainText:c,subtitleText:d,label:b});g.Nu(a.element,"ytp-offline-slate-single-text-line",!d);g.Nu(a.C,"ytp-offline-slate-bar-hidden",!c&&!d)}},A6=function(a,b){var c=(0,g.FD)();
this.module="heartbeat";this.trigger=a;this.j=b;this.C=c},cpb=function(a){g.zV.call(this,a);
var b=this;this.N=!1;this.Z=0;this.G=!1;this.B=new g.Bu(function(){var e=b.player.U(),f=b.getVideoData();B6(b)&&(Wob(b)?Xob(b,e,f):(Yob(b),Zob(b,e,f)))},0);
this.j=this.heartbeatParams=null;this.D=!1;this.K=new g.xl(1E3,6E4,1);this.sequenceNumber=0;this.offlineSlate=null;this.ma=new g.GE(void 0);this.Y=this.attestationResponse=void 0;this.utcOffsetMinutes=-(new Kob).getTimezoneOffset();this.C=new g.PK(this);g.L(this,this.B);g.L(this,this.C);Yob(this);$ob(this);this.C.T(a,"heartbeatparams",this.FE);this.C.T(a,"presentingplayerstatechange",this.Q1);this.C.T(a,"videoplayerreset",this.R1);this.C.T(a,g.fK("heartbeat"),this.onCueRangeEnter);this.D&&this.j&&
apb(this,void 0,this.j);var c=new g.eK(1E3,0x7ffffffffffff,{priority:1,namespace:"heartbeat"}),d=new g.eK(0x8000000000000,0x8000000000000,{id:"stream_end",priority:1,namespace:"heartbeat"});a.xf([c,d]);bpb(this)},bpb=function(a){var b=a.getVideoData();
b.Qm&&(b=b.botguardData)&&g.dLa(b,a.player.U())},Yob=function(a){var b=a.getVideoData();
if(b.Qm&&(b=new g.$Ka(b),g.oI.isInitialized()||3<=a.sequenceNumber)){var c=null;if(b.videoData.Pk){var d=g.aLa(b);if(d){c={};var e={};d=d.split("&");d=g.v(d);for(var f=d.next();!f.done;f=d.next())f=f.value.split("="),2===f.length&&(e[f[0]]=f[1]);e.r1a&&(c.webResponse=e.r1a);e.r1c&&(c.error=dpb[Number(e.r1c)]);c.challenge=b.videoData.Pk}}a.attestationResponse=c||void 0}},Wob=function(a){var b=a.getVideoData();
if(!g.yT(a.getVideoData())||b.j_)return!1;if(b.useInnertubeDrmService()&&b.K){a="playready"===b.K.flavor&&b.L("html5_innertube_heartbeats_for_playready");var c="widevine"===b.K.flavor&&b.L("html5_innertube_heartbeats_for_widevine");b=g.zR(b.K)&&b.L("html5_innertube_heartbeats_for_fairplay");return!(a||c||b)}return!0},epb=function(a){if(Wob(a))return!!a.heartbeatParams;
var b=a.getVideoData();return g.yT(a.getVideoData())&&b.useInnertubeDrmService()&&!b.Kl&&!b.oC?!1:!!b.heartbeatToken},C6=function(a,b){if(!a.B.isActive()&&a.N){var c=a.getVideoData();
if(epb(a)||c.isLivePlayback){if(void 0===b)if(a.G)if(a.D)b=7500;else{var d;b=(null==(d=a.heartbeatParams)?0:d.interval)?1E3*a.heartbeatParams.interval:a.getVideoData().jY||6E4}else b=1E3;a.B.start(b)}}},ipb=function(a,b,c){b.Oo&&(c=g.Jl(c,{internalipoverride:b.Oo}));
var d={cpn:b.clientPlaybackNonce};b.contextParams&&(d.context_params=b.contextParams);b.yb&&(d.kpt=b.yb);c=g.Jl(c,d);g.fC(c,{format:"RAW",method:"GET",timeout:3E4,onSuccess:function(e){if(!a.B.isActive()&&B6(a)){a.K.reset();a.sequenceNumber++;e=e.responseText;var f=fpb(e);if(f){a.player.Qa("onHeartbeat",f);var h="ok"===f.status?f.stop_heartbeat?2:0:"stop"===f.status?1:"live_stream_offline"===f.status?0:-1}else h=(h=e.match(gpb))?"0"===h[1]?0:1:-1;hpb(a,void 0,f,e,h)}},
onError:function(e){B6(a)&&D6(a,!0,"net-"+e.status)},
onTimeout:function(){B6(a)&&D6(a,!0,"timeout")},
withCredentials:!0})},Xob=function(a,b,c){var d;
if(null!=(d=a.heartbeatParams)&&d.url){var e=g.Jl(a.heartbeatParams.url,{request_id:g.ssa()});c.qa&&(e=g.Jl(e,{vvt:c.qa}),c.mdxEnvironment&&(e=g.Jl(e,{mdx_environment:c.mdxEnvironment})));g.zS(b,c.oauthToken).then(function(f){f&&(e=g.Jl(e,{access_token:f}));ipb(a,c,e)})}},B6=function(a){var b=a.getVideoData();
return 3===a.player.getPresentingPlayerType()||g.SG(a.player.Tb(a.getPlayerType()),4)?!1:epb(a)||b.isLivePlayback?!0:(E6(a),!1)},Zob=function(a,b,c){var d,e={videoId:c.videoId,
sequenceNumber:a.sequenceNumber,heartbeatServerData:null!=(d=a.qa)?d:c.heartbeatServerData};a.Y=a.attestationResponse;c.Qm&&(e.attestationResponse=a.Y);var f=g.UT(c),h;d=null!=(h=f.client)?h:{};d.utcOffsetMinutes=a.utcOffsetMinutes;e.context=f;e.cpn=c.clientPlaybackNonce;if(h="undefined"!==typeof Intl?(new Intl.DateTimeFormat).resolvedOptions().timeZone:null)d.timeZone=h;h={heartbeatChecks:[]};if(d=c.getPlayerResponse())c.heartbeatToken&&(e.heartbeatToken=c.heartbeatToken),(d=d.playabilityStatus)&&
(d=d.liveStreamability)&&d.liveStreamabilityRenderer&&h.heartbeatChecks.push("HEARTBEAT_CHECK_TYPE_LIVE_STREAM_STATUS");c.heartbeatToken&&h.heartbeatChecks.push("HEARTBEAT_CHECK_TYPE_YPC");if(g.IJ(b)){h.heartbeatChecks.push("HEARTBEAT_CHECK_TYPE_UNPLUGGED");f=jpb(a);d={};null!==f&&(d.clientPlayerPositionUtcMillis=f);var l,m;f=(null==(m=null==(l=a.player.Eb())?void 0:g.OV(l))?void 0:m.freePreviewWatchedDuration)||0;0<f&&(d.freePreviewWatchedDuration={seconds:""+f});h.unpluggedParams=d}e.heartbeatRequestParams=
h;c.isLivePlayback?(l=jpb(a),null!==l&&(e.playbackState||(e.playbackState={}),e.playbackState.playbackPosition={utcTimeMillis:l})):b.L("enable_heartbeat_vod_playback_position")&&(l=kpb(a),null!==l&&(e.playbackState||(e.playbackState={}),e.playbackState.playbackPosition={streamTimeMillis:l}));a.player.oa("heartbeatRequest",e);var n={timeout:3E4,onSuccess:function(p){if(!a.B.isActive()&&B6(a)){var q=a.getVideoData(),r=q.Qm&&null==a.Y,t;q.Qm=!(null==(t=p.heartbeatAttestationConfig)||!t.requiresAttestation)||
r;r=p.playabilityStatus;t=JSON.stringify(r)||"{}";p.authenticationMismatch&&a.player.va("authshear",{});var u=-1;var x=p.playabilityStatus;x&&(a.player.Qa("onHeartbeat",x),"OK"===x.status?u=p.stopHeartbeat?2:0:"UNPLAYABLE"===x.status?u=1:"LIVE_STREAM_OFFLINE"===x.status&&(u=0));a.sequenceNumber&&-1===u||a.K.reset();a.sequenceNumber++;p.heartbeatServerData&&(a.qa=p.heartbeatServerData);q.qC=p;(x=p.playerCueRangeSet)&&g.NQa(q,x);p.playerCueRanges&&0<p.playerCueRanges.length&&(q.cueRanges=p.playerCueRanges);
var B,F;(null==(B=p.progressBarConfig)?0:B.progressBarStartPosition)&&(null==(F=p.progressBarConfig)?0:F.progressBarEndPosition)&&(q.progressBarStartPosition=p.progressBarConfig.progressBarStartPosition,q.progressBarEndPosition=p.progressBarConfig.progressBarEndPosition);q.compositeLiveIngestionOffsetToken=p.compositeLiveIngestionOffsetToken;p.compositeLiveStatusToken!==q.compositeLiveStatusToken&&(q.compositeLiveStatusToken=p.compositeLiveStatusToken);q.oa("dataupdated");hpb(a,p,r,t,u)}},
onError:function(p){B6(a)&&D6(a,!0,"net-"+p.status)},
onTimeout:function(){B6(a)&&D6(a,!0,"timeout")}};
g.zS(b,g.OT(c)).then(function(p){p&&(n.ZU="Bearer "+p);g.HE(a.ma,"player/heartbeat",e,n)})},hpb=function(a,b,c,d,e){-1===e?(c="decode "+g.ug(d,3),D6(a,!1,c)):2===e?(E6(a),a.G=!0):(a.Z=0,a.B.stop(),1===e?(a.G=!1,c&&"PLAYABILITY_ERROR_CODE_EMBARGOED"===c.errorCode&&a.player.uo(!0),a.player.Fg("heartbeat.stop",2,a.yf(d)),g.qD("heartbeatActionPlayerHalted",lpb(c)),(null==b?0:b.videoTransitionEndpoint)&&c&&(b=b.videoTransitionEndpoint,(d=g.T(b,g.oT))&&mpb(a,d,c,{itct:null==b?void 0:b.clickTrackingParams}))):
(a.G=!0,d=0,a.D&&c&&(d=apb(a,b,c),a.player.oa("livestatedata",c)),d?C6(a,d):C6(a)))},apb=function(a,b,c){var d=c.liveStreamability&&c.liveStreamability.liveStreamabilityRenderer,e=!(!d||!(d.switchStreamsImmediately||d.transitionTiming&&"STREAM_TRANSITION_TIMING_IMMEDIATELY"===d.transitionTiming));
b=npb(a,b,d);var f=a.getVideoData(),h=a.player.Tb(a.getPlayerType()),l=h.isPlaying()&&!g.DT(f)&&!a.player.isAtLiveHead(a.getPlayerType());if(f.U().Vc()){var m,n=(null==(m=a.player.zf())?void 0:m.vc())||{};n.status=c.status||"";n.dvr=""+ +l;n["switch"]=""+ +e;n.ended=""+ +!(!d||!d.displayEndscreen);a.player.va("heartbeat",n)}if(l&&!e)return b;e=d&&d.streamTransitionEndpoint&&g.T(d.streamTransitionEndpoint,g.oT);if("STREAM_TRANSITION_TIMING_AT_STREAM_END"===(d&&d.transitionTiming))a.getVideoData().transitionEndpointAtEndOfStream=
e;else if(e&&mpb(a,e,c))return b;if("OK"===c.status.toUpperCase()){e=d&&d.broadcastId;m=a.j&&a.j.liveStreamability&&a.j.liveStreamability.liveStreamabilityRenderer&&a.j.liveStreamability.liveStreamabilityRenderer.broadcastId;l=e!==m&&null!=e;if(!g.BT(f)||l){var p={video_id:f.videoId};f.mM&&(p.is_live_destination="1");a.player.L("web_player_heartbeat_request_watch_next")||(p.disable_watch_next=!0,p.raw_watch_next_response=f.getWatchNextResponse());p.autonav_state=f.autonavState;p.oauth_token=f.oauthToken;
p.force_gvi=f.No;p.Am=f.Am;f.G&&(p.vss_credentials_token=f.G,p.vss_credentials_token_type=f.Mm);f.qa&&(p.vvt=f.qa);d=void 0;g.BT(f)?l&&(d=new A6("broadcastIdChanged",m+","+e),a.SI("HEARTBEAT_ACTION_TRIGGER_IMMEDIATE","HEARTBEAT_ACTION_TRANSITION_REASON_BROADCAST_ID_CHANGED",c)):(e&&(d=new A6("formatsReceived",""+e)),a.SI("HEARTBEAT_ACTION_TRIGGER_IMMEDIATE","HEARTBEAT_ACTION_TRANSITION_REASON_LIVE_STREAM_WENT_ONLINE",c));a.player.loadVideoByPlayerVars(p,void 0,void 0,void 0,d);return b}a.player.Gg("heartbeat",
a.getPlayerType())}d&&d.displayEndscreen&&(a.offlineSlate?(a=a.offlineSlate,a.K=!0,a.Gb&&a.api.oB()):g.NL(h)&&(f=(null==(p=a.player.zf())?void 0:p.vc())||{},a.player.va("hbse",f,!0),a.player.oB(),a.player.Qa("onLiveMediaEnded",c)));return b},npb=function(a,b,c){return a.player.L("web_player_use_heartbeat_poll_delay_ms")&&(a=Number(null==b?void 0:b.pollDelayMs))?a:(c=Number(null==c?void 0:c.pollDelayMs))?c:0},D6=function(a,b,c){var d=a.player.U();
if(!a.B.isActive()){a.B.stop();a.Z++;var e=b?"heartbeat.net":"heartbeat.servererror";var f=a.getVideoData();if(f.FZ||b&&!g.yT(a.getVideoData())&&!epb(a)&&f.isLivePlayback)f=!1;else{var h,l;(null==(l=a.heartbeatParams)?0:l.fB)?h=a.heartbeatParams.fB:h=f.rY||5;f=a.Z>=h}f?(g.qD("heartbeatActionPlayerHalted",b?{enforcedPolicyToHaltOnNetworkFailure:!0}:lpb()),(b=a.getVideoData())&&b.isLivePlayback?a.player.Fg(e,1,"Video playback interrupted. Please try again.",c):a.player.Fg(e,1,"Sorry, there was an error licensing this video.",
c)):(d.L("html5_report_non_fatal_heartbeat_error")&&a.player.Rr(e,{msg:c}),C6(a,a.K.getValue()),g.yl(a.K))}},lpb=function(a){var b={enforcedPolicyToHaltOnNetworkFailure:!1};
a&&(b.serializedServerContext=a.additionalLoggingData);return b},E6=function(a){a.Z=0;
a.B.stop();a.G=!1;a.sequenceNumber=0},$ob=function(a){var b=a.getVideoData(),c=a.player.U();
if(b.isLivePlayback)if(g.BOa(c.G)){a.D=!0;a.N=!0;if(!g.KJ(c)||g.IJ(c))a.offlineSlate=new Uob(a.player),g.L(a,a.offlineSlate),g.tU(a.player,a.offlineSlate.element,4);(b=b.getPlayerResponse())&&b.playabilityStatus&&(a.j=b.playabilityStatus);var d;"UNPLAYABLE"!==(null==(d=a.j)?void 0:d.status)&&(a.j?(d=npb(a,void 0,a.j.liveStreamability&&a.j.liveStreamability.liveStreamabilityRenderer))?C6(a,d):C6(a,7500):C6(a,1E3))}else a.player.Fg("html5.unsupportedlive",2,"HTML5_NO_AVAILABLE_FORMATS_FALLBACK","nolive.1");
else g.Gb(b.Da,"heartbeat")&&a.player.Gg("heartbeat",a.getPlayerType())},mpb=function(a,b,c,d){var e=b&&b.videoId;
return e?(a.player.Jo(e,Object.assign({},{autonav:"1"},d||{}),void 0,!0,!0,b,g.OT(a.getVideoData())),a.SI("HEARTBEAT_ACTION_TRIGGER_IMMEDIATE","HEARTBEAT_ACTION_TRANSITION_REASON_HAS_NEW_STREAM_TRANSITION_ENDPOINT",c),!0):!1},jpb=function(a){return(a=a.player.getProgressState(a.getPlayerType()).ingestionTime)&&isFinite(a)?""+Math.floor(1E3*a):null},kpb=function(a){return(a=a.player.getCurrentTime(a.getPlayerType()))&&isFinite(a)?""+Math.floor(1E3*a):null},fpb=function(a){try{var b=JSON.parse(a);
return null!=b?b:void 0}catch(c){}},opb={ERAS:["BC",
"AD"],ERANAMES:["Before Christ","Anno Domini"],NARROWMONTHS:"JFMAMJJASOND".split(""),STANDALONENARROWMONTHS:"JFMAMJJASOND".split(""),MONTHS:"January February March April May June July August September October November December".split(" "),STANDALONEMONTHS:"January February March April May June July August September October November December".split(" "),SHORTMONTHS:"Jan Feb Mar Apr May Jun Jul Aug Sep Oct Nov Dec".split(" "),STANDALONESHORTMONTHS:"Jan Feb Mar Apr May Jun Jul Aug Sep Oct Nov Dec".split(" "),
WEEKDAYS:"Sunday Monday Tuesday Wednesday Thursday Friday Saturday".split(" "),STANDALONEWEEKDAYS:"Sunday Monday Tuesday Wednesday Thursday Friday Saturday".split(" "),SHORTWEEKDAYS:"Sun Mon Tue Wed Thu Fri Sat".split(" "),STANDALONESHORTWEEKDAYS:"Sun Mon Tue Wed Thu Fri Sat".split(" "),NARROWWEEKDAYS:"SMTWTFS".split(""),STANDALONENARROWWEEKDAYS:"SMTWTFS".split(""),SHORTQUARTERS:["Q1","Q2","Q3","Q4"],QUARTERS:["1st quarter","2nd quarter","3rd quarter","4th quarter"],AMPMS:["AM","PM"],DATEFORMATS:["EEEE, MMMM d, y",
"MMMM d, y","MMM d, y","M/d/yy"],TIMEFORMATS:["h:mm:ss\u202fa zzzz","h:mm:ss\u202fa z","h:mm:ss\u202fa","h:mm\u202fa"],DATETIMEFORMATS:["{1} 'at' {0}","{1} 'at' {0}","{1}, {0}","{1}, {0}"],FIRSTDAYOFWEEK:6,WEEKENDRANGE:[5,6],FIRSTWEEKCUTOFFDAY:5},ppb=opb;ppb=opb;var dpb=["ATTESTATION_ERROR_UNKNOWN","ATTESTATION_ERROR_VM_NOT_INITIALIZED","ATTESTATION_ERROR_VM_NO_RESPONSE","ATTESTATION_ERROR_VM_TIMEOUT","ATTESTATION_ERROR_VM_INTERNAL_ERROR"];g.k=Kob.prototype;g.k.bW=ppb.FIRSTDAYOFWEEK;g.k.cW=ppb.FIRSTWEEKCUTOFFDAY;
g.k.clone=function(){var a=new Kob(this.date);a.bW=this.bW;a.cW=this.cW;return a};
g.k.getFullYear=function(){return this.date.getFullYear()};
g.k.getYear=function(){return this.getFullYear()};
g.k.getMonth=function(){return this.date.getMonth()};
g.k.getDate=function(){return this.date.getDate()};
g.k.getTime=function(){return this.date.getTime()};
g.k.getDay=function(){return this.date.getDay()};
g.k.getUTCFullYear=function(){return this.date.getUTCFullYear()};
g.k.getUTCMonth=function(){return this.date.getUTCMonth()};
g.k.getUTCDate=function(){return this.date.getUTCDate()};
g.k.getUTCDay=function(){return this.date.getDay()};
g.k.getUTCHours=function(){return this.date.getUTCHours()};
g.k.getUTCMinutes=function(){return this.date.getUTCMinutes()};
g.k.getTimezoneOffset=function(){return this.date.getTimezoneOffset()};
g.k.set=function(a){this.date=new Date(a.getFullYear(),a.getMonth(),a.getDate())};
g.k.setFullYear=function(a){this.date.setFullYear(a)};
g.k.setYear=function(a){this.setFullYear(a)};
g.k.setMonth=function(a){this.date.setMonth(a)};
g.k.setDate=function(a){this.date.setDate(a)};
g.k.setTime=function(a){this.date.setTime(a)};
g.k.setUTCFullYear=function(a){this.date.setUTCFullYear(a)};
g.k.setUTCMonth=function(a){this.date.setUTCMonth(a)};
g.k.setUTCDate=function(a){this.date.setUTCDate(a)};
g.k.add=function(a){if(a.years||a.months){var b=this.getMonth()+a.months+12*a.years,c=this.getYear()+Math.floor(b/12);b%=12;0>b&&(b+=12);a:{switch(b){case 1:var d=0!=c%4||0==c%100&&0!=c%400?28:29;break a;case 5:case 8:case 10:case 3:d=30;break a}d=31}d=Math.min(d,this.getDate());this.setDate(1);this.setFullYear(c);this.setMonth(b);this.setDate(d)}a.days&&(c=this.getYear(),b=0<=c&&99>=c?-1900:0,a=new Date((new Date(c,this.getMonth(),this.getDate(),12)).getTime()+864E5*a.days),this.setDate(1),this.setFullYear(a.getFullYear()+
b),this.setMonth(a.getMonth()),this.setDate(a.getDate()),w6(this,a.getDate()))};
g.k.equals=function(a){return!(!a||this.getYear()!=a.getYear()||this.getMonth()!=a.getMonth()||this.getDate()!=a.getDate())};
g.k.toString=function(){var a=this.getFullYear(),b=0>a?"-":1E4<=a?"+":"";return[b+Gob(Math.abs(a),b?6:4),Gob(this.getMonth()+1,2),Gob(this.getDate(),2)].join("")+""};
g.k.valueOf=function(){return this.date.valueOf()};var qpb=new g.hw("addUpcomingEventReminderEndpoint");var rpb=new g.hw("removeUpcomingEventReminderEndpoint");var spb=new g.hw("updateUpcomingEventReminderButtonStateCommand");var Nob=new g.hw("upcomingEventReminderButtonRenderer"),Tob=new g.hw("upcomingEventReminderButtonStateRenderer");g.w(x6,g.xU);x6.prototype.hide=function(){this.buttonElement&&this.buttonElement.removeAttribute("aria-haspopup");g.xU.prototype.hide.call(this)};
x6.prototype.show=function(){this.buttonElement&&this.buttonElement.setAttribute("aria-haspopup","true");g.xU.prototype.show.call(this)};
x6.prototype.ya=function(){g.vb(this.j);g.xU.prototype.ya.call(this)};g.w(y6,g.U);
y6.prototype.G=function(){if(this.toggleButtonRenderer){var a=this.toggleButtonRenderer;a.isToggled?this.C(a.toggledServiceEndpoint):this.C(a.defaultServiceEndpoint);a.isToggled=!a.isToggled;z6(this)}else if(this.upcomingEventReminderButtonRenderer)if(this.j&&this.j.Gb)this.j.Qb();else{var b=Qob(this);b&&this.C(b.serviceEndpoint||b.command);b=(null==(a=g.T(null==b?void 0:b.command,g.$F))?void 0:a.commands)||[];a:{a=g.v(b);for(var c=a.next();!c.done;c=a.next()){var d=b=void 0;if(c=null==(b=g.T(c.value,
g.cfb))?void 0:null==(d=b.popup)?void 0:d.menuPopupRenderer){a=c;break a}}a=void 0}this.j||(this.j=new x6(this.J,this.buttonElement),this.j.Ea(this.element),g.L(this,this.j),this.j.subscribe("reminderMenuItemClicked",this.C,this));b=this.j;b.menuPopupRenderer=a;Mob(b)}};
y6.prototype.C=function(a){var b=g.T(a,qpb),c=g.T(a,rpb);if(a&&(b||c)){if(b){var d=b;var e="notification/add_upcoming_event_reminder"}else c&&(d=c,e="notification/remove_upcoming_event_reminder");if(e&&d&&d.params)for(Sob(this,e,d.params),a=g.v(d.commands||[]),b=a.next();!b.done;b=a.next())if((b=b.value)&&g.T(b,spb)){this.B=g.T(b,spb).state;z6(this);break}}};g.w(Uob,g.U);g.k=Uob.prototype;g.k.getPlayerType=function(){if(8===this.api.getPresentingPlayerType())return 1};
g.k.getVideoData=function(){return this.api.getVideoData(this.getPlayerType())};
g.k.Ra=function(a){var b,c,d=null==a?void 0:null==(b=a.liveStreamability)?void 0:null==(c=b.liveStreamabilityRenderer)?void 0:c.offlineSlate;if(d){this.B=a;b=d.liveStreamOfflineSlateRenderer;b.canShowCountdown?this.f0():Vob(this,b);var e,f,h,l;if(c=null==a?void 0:null==(e=a.liveStreamability)?void 0:null==(f=e.liveStreamabilityRenderer)?void 0:null==(h=f.offlineSlate)?void 0:null==(l=h.liveStreamOfflineSlateRenderer)?void 0:l.thumbnail){e=0;f=null;h=c.thumbnails;for(l=0;l<h.length;l++)h[l].width>
e&&(e=h[l].width||0,f=h[l].url);f&&(this.background.style.backgroundImage="url("+f+")")}else this.background.style.backgroundImage="";b.actionButtons||b.reminderButton?(this.j||(this.j=new y6(this.api),this.j.Ea(this.Ga("ytp-offline-slate-buttons")),g.L(this,this.j)),Oob(this.j,b.actionButtons&&b.actionButtons[0],b.reminderButton)):this.j&&Oob(this.j,null,null);this.B=a}else this.B=null;this.k0()};
g.k.k0=function(a){if(8===this.api.getPresentingPlayerType())var b=!0;else{var c=this.api.Tb(),d=this.getVideoData();b=d.isLivePlayback&&(g.NL(c)||g.SG(c,2)||g.SG(c,64));var e=2===d.autonavState&&g.SG(c,2);c=c.isPlaying()&&!g.DT(d)&&!this.api.isAtLiveHead(void 0,!0);b=b&&!c&&!e}b&&this.B?this.Gb?(null==a?0:g.UG(a,2))&&!this.getVideoData().Ul&&(g.Lu(this.element,"ytp-offline-slate-collapsed"),this.D.stop(),g.Lu(this.C,"ytp-offline-slate-bar-fade"),this.G.start()):(this.show(),this.D.start(),this.api.oa("offlineslatestatechange"),
this.K&&this.api.oB()):this.Gb&&(this.hide(),this.api.oa("offlineslatestatechange"))};
g.k.f0=function(){var a,b,c,d,e=null==(a=this.B)?void 0:null==(b=a.liveStreamability)?void 0:null==(c=b.liveStreamabilityRenderer)?void 0:null==(d=c.offlineSlate)?void 0:d.liveStreamOfflineSlateRenderer;e&&(a=Math.floor(g.lb()/1E3),b=e.canShowCountdown&&Number(e.scheduledStartTime),!b||b<=a?(Vob(this,e),this.countdownTimer.stop()):(Vob(this,e,g.aH(b-a)),g.Cu(this.countdownTimer)))};
g.k.ya=function(){this.countdownTimer.dispose();this.countdownTimer=null;g.U.prototype.ya.call(this)};A6.prototype.B=function(a){return this.trigger&&a.trigger?this.module===a.module&&this.trigger===a.trigger&&this.j===a.j:!1};
A6.prototype.isExpired=function(){return 6E4<(0,g.FD)()-this.C};
A6.prototype.toString=function(){return this.module+":"+this.trigger+":"+this.j};g.w(cpb,g.zV);g.k=cpb.prototype;g.k.ya=function(){E6(this);this.player.lf("heartbeat");g.zV.prototype.ya.call(this)};
g.k.onCueRangeEnter=function(){this.N=!0;C6(this,2E3)};
g.k.FE=function(a){this.heartbeatParams=a;C6(this,2E3)};
g.k.Q1=function(a){var b;8!==this.player.getPresentingPlayerType()&&"UNPLAYABLE"!==(null==(b=this.j)?void 0:b.status)&&(g.SG(a.state,2)||g.SG(a.state,64)?(E6(this),this.D&&(this.N=!0,C6(this,1E3))):(g.SG(a.state,1)||g.SG(a.state,8))&&C6(this,2E3))};
g.k.R1=function(){3!==this.player.getPresentingPlayerType()&&C6(this,2E3)};
g.k.getPlayerType=function(){if(8===this.player.getPresentingPlayerType())return 1};
g.k.getVideoData=function(){return this.player.getVideoData(this.getPlayerType())};
g.k.El=function(a){switch(a){case 4:case 3:return!1}return!0};
g.k.SI=function(a,b,c){a={trigger:a,reason:b};c&&(a.serializedServerContext=c.additionalLoggingData);g.qD("heartbeatActionPlayerTransitioned",a)};
g.k.yf=function(a){var b="LICENSE",c=fpb(a);if(c)return c.reason||g.XV[b]||"";(a=a.match(gpb))&&(a=Number(a[1]))&&(b=g.XAa(a));return g.XV[b]||""};
g.k.XD=function(){return!!this.offlineSlate&&this.offlineSlate.Gb};
var gpb=/^GLS\/1.0 (\d+) (\w+).*?\r\n\r\n([\S\s]*)$/;g.yV("heartbeat",cpb);})(_yt_player);
